blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/PhilopaterSh/Ph.Sh-Subdomain/discussions
    about: Ask a question or start a discussion with the community.
